### ISSUE TITLE
Setup VM environment

### ISSUE THREAD

**Issue by nehalecky** [nehalecky/CS7641-Machine-Learning#5]
With all the usual suspects. 
- [x] Ubuntu box via Vagrant [ #6 ]
- [x] shell script bootstrap [ #7 ]
- [x] Conda install of pandas, scikit learn, and others. [ #7 ]
- [ ] Integrate with Paver (https://pythonhosted.org/Paver/index.html)
